// Desktop launcher release channel (GitHub Releases).
//
// `dpx` and the desktop shell both consume this contract; the machine-readable
// shape is specified in `docs/desktop-release.md`. The desktop shell implements
// the same rules in Rust (`desktop-shell/src-tauri/src/update.rs`).
//
// A published desktop release has the tag `desktop-v<version>` and carries:
//   - `desktop-latest.json`                     the manifest below
//   - `DSH-DeepSeek-Harness-Desktop-<version>-x64.exe`   the launcher
//
// Manifest (`DPXDesktopRelease`, schemaVersion 1):
//   { schemaVersion, kind, channel, version, tag, platform, assetName,
//     assetUrl, sha256, size, publishedAt, notes, sig? }
//
// `sig` is an **optional** publisher signature (`{ algorithm: 'ed25519',
// signature: <base64> , keyId? }`). It is never produced here; this module only
// verifies it, and only when a trusted public key is configured. The signed
// message is defined by `desktopSignatureMessage()` and deliberately covers the
// digest instead of the manifest bytes, because the manifest is generated by
// more than one tool (PowerShell `ConvertTo-Json` and Node `JSON.stringify`
// disagree on bytes) while the digest is a single lowercase hex string.
//
// The install stamp `desktop/.dpx-desktop.json` is written by two programs:
// this module (ISO `installedAt`) and the desktop shell (epoch
// `installedAtMillis`, `update.rs:515`). Readers accept both shapes, and the
// stamp `schemaVersion` is validated against `DESKTOP_STAMP_SCHEMA_VERSIONS`
// instead of being accepted silently.

import { createHash, createPublicKey, verify as cryptoVerify } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { HttpError, defaultProxy, httpGet, httpGetBuffer, httpGetJson } from './http.js';

export const DESKTOP_RELEASE_KIND = 'DPXDesktopRelease';
export const DESKTOP_RELEASE_SCHEMA_VERSION = 1;
export const DESKTOP_RELEASE_CHANNEL = 'desktop';
export const DESKTOP_MANIFEST_ASSET = 'desktop-latest.json';
export const DESKTOP_ASSET_PREFIX = 'DSH-DeepSeek-Harness-Desktop-';
export const DESKTOP_LAUNCHER_DIR = 'desktop';
export const DESKTOP_LAUNCHER_NAME = 'DSH DeepSeek Harness Desktop.exe';
export const DESKTOP_STAMP_NAME = '.dpx-desktop.json';
export const DESKTOP_TAG_PREFIX = 'desktop-v';
export const DESKTOP_PLATFORM = 'win32-x64';
export const DEFAULT_DESKTOP_REPOSITORY = 'T-Auto/dsh-dpx';
export const DEFAULT_DESKTOP_SOURCE = `github:${DEFAULT_DESKTOP_REPOSITORY}`;
export const DESKTOP_USER_AGENT = 'dsh-dpx-desktop-updater';

/**
 * GitHub REST base used by the pre-release lookup. Exported so a local test
 * server (or a GitHub Enterprise host) can be injected through the `apiBase`
 * option or the `DPX_GITHUB_API` variable without changing any call signature.
 */
export const DEFAULT_DESKTOP_GITHUB_API = 'https://api.github.com';
export const DESKTOP_GITHUB_API_ENV = 'DPX_GITHUB_API';

/**
 * Stamp schema versions this module understands. A stamp outside the list is
 * reported as damaged by `readDesktopStamp()` instead of being read as if it
 * were version 1 — a future shell writing v2 must not be silently misread by an
 * older dpx.
 */
export const DESKTOP_STAMP_SCHEMA_VERSIONS = Object.freeze([1]);

/** Signature contract of `manifest.sig`. Only Ed25519 is supported. */
export const DESKTOP_SIGNATURE_ALGORITHM = 'ed25519';
export const DESKTOP_SIGNATURE_DOMAIN = 'dpx-desktop-release/v1';
export const DESKTOP_PUBLIC_KEY_ENV = 'DPX_DESKTOP_PUBLIC_KEY';
export const DESKTOP_PUBLIC_KEYS_ENV = 'DPX_DESKTOP_PUBLIC_KEYS';

export function desktopDir(envRoot) {
  return join(resolve(envRoot), DESKTOP_LAUNCHER_DIR);
}

export function desktopLauncherPath(envRoot) {
  return join(desktopDir(envRoot), DESKTOP_LAUNCHER_NAME);
}

export function desktopStampPath(envRoot) {
  return join(desktopDir(envRoot), DESKTOP_STAMP_NAME);
}

export function desktopAssetName(version) {
  return `${DESKTOP_ASSET_PREFIX}${version}-x64.exe`;
}

export function desktopTag(version) {
  return `${DESKTOP_TAG_PREFIX}${version}`;
}

/**
 * Parse a release source.
 *
 * - `github`                → the latest published release of the default repo
 * - `github:owner/repo`     → the latest published release of that repo
 * - `github:owner/repo@tag` → one exact release tag
 * - `https://…` / `http://…` → a manifest URL (self-hosted or a local test server)
 * - `file:/…` or a path      → a manifest file on disk (offline testing)
 */
export function parseDesktopSource(source = DEFAULT_DESKTOP_SOURCE) {
  const value = String(source ?? '').trim() || DEFAULT_DESKTOP_SOURCE;
  if (/^https?:\/\//i.test(value)) return { kind: 'url', source: value, manifestUrl: value };
  if (/^file:/i.test(value)) {
    const url = new URL(value);
    return { kind: 'file', source: value, manifestPath: fileURLToPath(url) };
  }
  if (!value.startsWith('github:')) {
    if (isAbsolute(value) || value.startsWith('.') || value.includes('\\') || value.includes('/')) {
      return { kind: 'file', source: value, manifestPath: resolve(value) };
    }
    throw new Error(`Unsupported desktop release source ${JSON.stringify(value)}. Use github[:owner/repo][@tag], an https manifest URL, or a local manifest path.`);
  }
  const spec = value.slice('github:'.length).trim() || DEFAULT_DESKTOP_REPOSITORY;
  const at = spec.lastIndexOf('@');
  const repository = (at > 0 ? spec.slice(0, at) : spec).trim();
  const tag = at > 0 ? spec.slice(at + 1).trim() : undefined;
  if (!/^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/.test(repository)) {
    throw new Error(`Invalid GitHub repository in desktop release source: ${JSON.stringify(repository)}.`);
  }
  return { kind: 'github', source: value, repository, tag: tag || undefined };
}

export function desktopManifestUrl(parsed, { tag } = {}) {
  if (parsed.kind === 'url') return parsed.manifestUrl;
  const effectiveTag = tag ?? parsed.tag;
  const suffix = effectiveTag
    ? `releases/download/${encodeURIComponent(effectiveTag)}`
    : 'releases/latest/download';
  return `https://github.com/${parsed.repository}/${suffix}/${DESKTOP_MANIFEST_ASSET}`;
}

/**
 * Compare two dotted versions (`1.2.3-alpha.1`); returns -1, 0, or 1.
 *
 * Core parts compare numerically and a missing part counts as `0`, so
 * `1.0` === `1.0.0` — this matches the Rust implementation, which already uses
 * `unwrap_or("0")` for absent parts.
 *
 * Pre-release identifiers follow semver precedence and are compared one
 * identifier at a time: numeric identifiers compare numerically (`rc.10` >
 * `rc.2`, which a whole-string comparison gets backwards), numeric identifiers
 * rank below alphanumeric ones, and a shorter identifier list ranks lower
 * (`alpha` < `alpha.1`). A version without a pre-release suffix stays newer
 * than the same version with one (`1.0.0` > `1.0.0-rc.1`).
 */
export function compareVersions(left, right) {
  const parse = value => String(value ?? '').trim().replace(/^v/i, '').split('+')[0];
  const split = value => {
    const [core, ...rest] = parse(value).split('-');
    return { parts: core.split('.').map(part => (/^\d+$/.test(part) ? Number(part) : part)), pre: rest.join('-') };
  };
  const a = split(left);
  const b = split(right);
  const length = Math.max(a.parts.length, b.parts.length);
  for (let index = 0; index < length; index += 1) {
    const x = a.parts[index] ?? 0;
    const y = b.parts[index] ?? 0;
    if (x === y) continue;
    if (typeof x === 'number' && typeof y === 'number') return x < y ? -1 : 1;
    const xs = String(x);
    const ys = String(y);
    if (xs === ys) continue;
    return xs < ys ? -1 : 1;
  }
  if (a.pre === b.pre) return 0;
  if (!a.pre) return 1;
  if (!b.pre) return -1;
  return comparePrerelease(a.pre, b.pre);
}

/** Semver precedence for two non-empty pre-release strings. */
function comparePrerelease(left, right) {
  const a = left.split('.');
  const b = right.split('.');
  const length = Math.max(a.length, b.length);
  for (let index = 0; index < length; index += 1) {
    const x = a[index];
    const y = b[index];
    if (x === undefined) return -1;
    if (y === undefined) return 1;
    if (x === y) continue;
    const numeric = /^\d+$/.test(x);
    if (numeric !== /^\d+$/.test(y)) return numeric ? -1 : 1;
    if (numeric) return Number(x) < Number(y) ? -1 : 1;
    return x < y ? -1 : 1;
  }
  return 0;
}

/**
 * Decode a base64 (or base64url, padded or not) value strictly.
 *
 * `Buffer.from(text, 'base64')` silently drops invalid characters, so the
 * decode is only accepted when it round-trips back to the same text.
 */
function decodeBase64(value) {
  let text = String(value ?? '').trim().replace(/-/g, '+').replace(/_/g, '/');
  if (!text || !/^[A-Za-z0-9+/]+={0,2}$/.test(text) || text.length % 4 === 1) return undefined;
  text += '='.repeat((4 - (text.length % 4)) % 4);
  const buffer = Buffer.from(text, 'base64');
  return buffer.toString('base64') === text ? buffer : undefined;
}

/**
 * Parse one trusted desktop public key.
 *
 * Accepted inputs: an Ed25519 `KeyObject`, a PEM `PUBLIC KEY` block, a base64
 * SPKI DER blob, or the base64 of a raw 32-byte Ed25519 key. Anything else
 * throws, because an unreadable key must never silently disable verification.
 */
export function parseDesktopPublicKey(value) {
  if (value && typeof value === 'object' && value.type === 'public' && typeof value.export === 'function') return value;
  const text = String(value ?? '').trim();
  if (!text) return undefined;
  if (/-----BEGIN [A-Z ]*PUBLIC KEY-----/.test(text)) {
    try {
      return createPublicKey(text);
    } catch (error) {
      throw new Error(`桌面公钥不是有效的 PEM：${error.message}`);
    }
  }
  const der = decodeBase64(text);
  if (!der) throw new Error('桌面公钥必须是 PEM、base64 的 SPKI DER，或 base64 的原始 32 字节 Ed25519 公钥。');
  try {
    if (der.length === 32) {
      return createPublicKey({ key: { kty: 'OKP', crv: 'Ed25519', x: der.toString('base64url') }, format: 'jwk' });
    }
    return createPublicKey({ key: der, format: 'der', type: 'spki' });
  } catch (error) {
    throw new Error(`桌面公钥无法解析：${error.message}`);
  }
}

function splitKeyList(value) {
  return String(value ?? '').split(/[\s,;]+/).map(item => item.trim()).filter(Boolean);
}

/**
 * Every trusted desktop public key, from explicit options and/or the
 * environment. Returns `[]` when nothing is configured — which is what keeps
 * signature checking an opt-in enhancement.
 *
 * - `publicKey` / `publicKeys` — explicit option, a key or a list of keys.
 * - `DPX_DESKTOP_PUBLIC_KEY`  — one PEM block, or one base64 key.
 * - `DPX_DESKTOP_PUBLIC_KEYS` — several base64 keys separated by `,` `;` or
 *   whitespace (a PEM block cannot be listed here, it contains newlines).
 *
 * The public key is **never** read from the manifest: a manifest that carried
 * its own key could be forged together with it.
 */
export function desktopPublicKeys({ publicKey, publicKeys, env = process.env } = {}) {
  const sources = [];
  const push = value => {
    for (const item of Array.isArray(value) ? value : [value]) {
      if (item === undefined || item === null) continue;
      if (Array.isArray(item)) push(item);
      else if (String(item).trim()) sources.push(item);
    }
  };
  push(publicKey);
  push(publicKeys);
  const single = env?.[DESKTOP_PUBLIC_KEY_ENV];
  if (single !== undefined && single !== null && String(single).trim()) {
    push(String(single).includes('-----BEGIN') ? String(single).trim() : splitKeyList(single));
  }
  const list = env?.[DESKTOP_PUBLIC_KEYS_ENV];
  if (list !== undefined && list !== null && String(list).trim()) push(splitKeyList(list));
  const keys = [];
  for (const source of sources) {
    const key = parseDesktopPublicKey(source);
    if (key) keys.push(key);
  }
  return keys;
}

/**
 * The exact bytes a `manifest.sig` Ed25519 signature covers.
 *
 * Signing the digest instead of the manifest document is deliberate: the
 * manifest is produced by more than one tool (PowerShell `ConvertTo-Json` in
 * the build script, Node `JSON.stringify` here) and the two do not agree on
 * bytes, whereas `sha256` is one lowercase hex string everywhere. Because the
 * downloader already rejects an artifact whose digest differs from this value,
 * a valid signature transitively authenticates the installed bytes.
 *
 * Message (UTF-8, `\n` separated, trailing newline):
 *   `dpx-desktop-release/v1\n<version>\n<assetName>\n<sha256>\n`
 */
export function desktopSignatureMessage(manifest) {
  const version = String(manifest?.version ?? '').trim();
  const assetName = String(manifest?.assetName ?? '').trim();
  const sha256 = normalizeSha256(manifest?.sha256);
  if (!version || !sha256) {
    throw new Error('无法构造桌面清单的签名消息：清单缺少 version 或 sha256。');
  }
  return Buffer.from(`${DESKTOP_SIGNATURE_DOMAIN}\n${version}\n${assetName}\n${sha256}\n`, 'utf8');
}

/**
 * Verify `manifest.sig` against the trusted public keys.
 *
 * Contract:
 * - no key configured → nothing is verified and nothing is rejected (the
 *   signature check stays an opt-in enhancement, so existing unsigned
 *   manifests keep installing);
 * - key configured + `sig` verifies → `{ signed: true, verified: true }`;
 * - key configured + `sig` present but unusable → throws (Chinese message);
 * - key configured + no `sig` → throws unless `requireSignature: false`,
 *   because otherwise stripping the signature would bypass the whole check.
 */
export function verifyManifestSignature(manifest, { keys, publicKey, publicKeys, env = process.env, requireSignature = true } = {}) {
  const trusted = keys ?? desktopPublicKeys({ publicKey, publicKeys, env });
  const version = String(manifest?.version ?? '').trim() || '未知版本';
  const sig = manifest?.sig;
  const problem = manifest?.sigProblem;
  if (!trusted.length) {
    return {
      signed: Boolean(sig) || Boolean(problem),
      verified: false,
      reason: problem ? 'unsupported-signature' : sig ? 'no-public-key' : 'unsigned',
      ...(problem ? { message: problem } : {}),
    };
  }
  if (problem) {
    throw new Error(`桌面发布清单 ${version} 带了一个无法校验的签名：${problem}拒绝安装。`);
  }
  if (!sig) {
    if (requireSignature === false) return { signed: false, verified: false, reason: 'unsigned' };
    throw new Error(`桌面发布清单 ${version} 没有 sig，但已配置桌面公钥（${DESKTOP_PUBLIC_KEY_ENV} / ${DESKTOP_PUBLIC_KEYS_ENV}）——拒绝安装未签名的清单。`);
  }
  const signature = decodeBase64(sig.signature);
  if (!signature || signature.length !== 64) {
    throw new Error(`桌面发布清单 ${version} 的 sig.signature 不是 64 字节的 base64 Ed25519 签名。`);
  }
  const message = desktopSignatureMessage(manifest);
  for (const key of trusted) {
    try {
      if (cryptoVerify(null, message, key, signature)) {
        return { signed: true, verified: true, algorithm: DESKTOP_SIGNATURE_ALGORITHM, ...(sig.keyId ? { keyId: sig.keyId } : {}) };
      }
    } catch {
      // A key of another type cannot verify an Ed25519 signature; try the next.
    }
  }
  throw new Error(`桌面发布清单 ${version} 的签名验证失败：没有任何已配置的桌面公钥能验证它。拒绝安装（清单可能被篡改，或发布方已经轮换密钥）。`);
}

/**
 * Read `sig` leniently. A signature this module cannot even parse is not thrown
 * here: with no trusted key configured the manifest must still install (current
 * behaviour), and with a key configured `verifyManifestSignature()` turns
 * `sigProblem` into a rejection.
 */
function normalizeSignature(value, version) {
  if (value === undefined || value === null) return {};
  if (typeof value !== 'object' || Array.isArray(value)) {
    return { sigProblem: `sig 必须是对象，收到 ${Array.isArray(value) ? 'array' : typeof value}。` };
  }
  const algorithm = String(value.algorithm ?? '').trim().toLowerCase();
  if (algorithm !== DESKTOP_SIGNATURE_ALGORITHM) {
    return { sigProblem: `sig.algorithm ${JSON.stringify(value.algorithm)} 不受支持，只支持 ${DESKTOP_SIGNATURE_ALGORITHM}。` };
  }
  const signature = String(value.signature ?? '').trim();
  if (!decodeBase64(signature)) return { sigProblem: 'sig.signature 不是有效的 base64。' };
  const keyId = value.keyId === undefined || value.keyId === null ? undefined : String(value.keyId).trim() || undefined;
  return { sig: { algorithm, signature, ...(keyId ? { keyId } : {}) } };
}

export function normalizeManifest(raw, { source, manifestUrl } = {}) {
  if (!raw || typeof raw !== 'object') throw new Error('Desktop release manifest is not a JSON object.');
  if (raw.kind && raw.kind !== DESKTOP_RELEASE_KIND) {
    throw new Error(`Unexpected desktop release manifest kind ${JSON.stringify(raw.kind)}; expected ${DESKTOP_RELEASE_KIND}.`);
  }
  const version = String(raw.version ?? '').trim().replace(/^v/i, '');
  if (!version) throw new Error('Desktop release manifest has no version.');
  const sha256 = normalizeSha256(raw.sha256);
  if (!sha256) throw new Error(`Desktop release manifest for ${version} has no sha256 digest.`);
  const assetName = String(raw.assetName ?? desktopAssetName(version)).trim();
  let assetUrl = raw.assetUrl ? String(raw.assetUrl).trim() : undefined;
  if (assetUrl && manifestUrl) assetUrl = new URL(assetUrl, manifestUrl).href;
  if (assetUrl && /^file:/i.test(assetUrl)) {
    // Keep file: URLs intact; the downloader resolves them locally.
  } else if (!assetUrl && manifestUrl && /^https?:/i.test(manifestUrl)) {
    assetUrl = new URL(encodeURIComponent(assetName), manifestUrl.replace(/[^/]*$/, '')).href;
  }
  const { sig, sigProblem } = normalizeSignature(raw.sig, version);
  return {
    schemaVersion: Number(raw.schemaVersion ?? DESKTOP_RELEASE_SCHEMA_VERSION),
    kind: DESKTOP_RELEASE_KIND,
    channel: String(raw.channel ?? DESKTOP_RELEASE_CHANNEL),
    version,
    tag: raw.tag ? String(raw.tag) : undefined,
    platform: String(raw.platform ?? DESKTOP_PLATFORM),
    assetName,
    assetUrl,
    sha256,
    size: Number.isFinite(Number(raw.size)) ? Number(raw.size) : undefined,
    publishedAt: raw.publishedAt ? String(raw.publishedAt) : undefined,
    notes: raw.notes ? String(raw.notes) : undefined,
    ...(sig ? { sig } : {}),
    ...(sigProblem ? { sigProblem } : {}),
    source: source ?? DEFAULT_DESKTOP_SOURCE,
    manifestUrl,
  };
}

export function normalizeSha256(value) {
  if (!value) return undefined;
  const hex = String(value).trim().replace(/^sha256:/i, '').toLowerCase();
  return /^[0-9a-f]{64}$/.test(hex) ? hex : undefined;
}

/**
 * Parse a manifest document. Tolerates a UTF-8 BOM, because PowerShell's
 * `Set-Content -Encoding utf8` (and several editors) add one and it would
 * otherwise be an unhelpful "Unexpected token" failure.
 */
export function parseManifestText(text, { source, manifestUrl } = {}) {
  let raw;
  try {
    raw = JSON.parse(String(text).replace(/^\uFEFF/, ''));
  } catch (error) {
    throw new Error(`桌面发布清单不是有效 JSON（${manifestUrl ?? source ?? '未知来源'}）：${error.message}`);
  }
  return normalizeManifest(raw, { source, manifestUrl });
}

export function sha256Of(buffer) {
  return createHash('sha256').update(buffer).digest('hex');
}

/** The manifest describing the desktop launcher bundled in this dpx package. */
export function bundledDesktopManifestPath() {
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'windows', 'desktop-manifest.json');
}

export async function readBundledDesktopManifest() {
  const path = bundledDesktopManifestPath();
  if (!existsSync(path)) return undefined;
  try {
    return parseManifestText(await readFile(path, 'utf8'), { source: 'bundled', manifestUrl: path });
  } catch {
    return undefined;
  }
}

/**
 * Effective GitHub REST base for one call.
 *
 * Precedence: explicit `apiBase` argument → `DPX_GITHUB_API` → the public
 * default. Tests point `apiBase` (or the variable) at their local HTTP server;
 * nothing else about the call changes, and every existing caller keeps the
 * default because both alternatives are optional.
 */
export function desktopGithubApi(apiBase, env = process.env) {
  const value = String(apiBase ?? env?.[DESKTOP_GITHUB_API_ENV] ?? '').trim() || DEFAULT_DESKTOP_GITHUB_API;
  return value.replace(/\/+$/, '');
}

function githubHeaders(env) {
  const token = env?.DPX_GITHUB_TOKEN?.trim() || env?.GITHUB_TOKEN?.trim() || env?.GH_TOKEN?.trim();
  return {
    'User-Agent': DESKTOP_USER_AGENT,
    Accept: 'application/vnd.github+json',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };
}

/**
 * Find the newest prerelease desktop tag through the GitHub API. Only used when
 * the caller explicitly opts into prereleases, because `/releases/latest`
 * deliberately ignores them.
 *
 * `apiBase` is optional and additive; every existing call signature is
 * unchanged and keeps hitting `https://api.github.com`.
 */
export async function resolveLatestPrereleaseTag(repository, { proxy, env = process.env, timeout, apiBase } = {}) {
  const releases = await httpGetJson(`${desktopGithubApi(apiBase, env)}/repos/${repository}/releases?per_page=30`, {
    proxy: proxy ?? defaultProxy(env),
    headers: githubHeaders(env),
    timeout,
  });
  const candidates = (Array.isArray(releases) ? releases : [])
    .filter(release => release && !release.draft && String(release.tag_name ?? '').startsWith(DESKTOP_TAG_PREFIX))
    .map(release => ({ tag: String(release.tag_name), version: String(release.tag_name).slice(DESKTOP_TAG_PREFIX.length) }))
    .sort((a, b) => compareVersions(b.version, a.version));
  return candidates[0]?.tag;
}

/**
 * Fetch the newest desktop release manifest for a source.
 * Throws `HttpError` with status 404 when the channel has no published release.
 *
 * Source coverage (kept explicit because the options do not apply uniformly):
 * - `github:` — `prerelease` and `tag` both apply; `tag` wins over `prerelease`;
 * - `https:` / `http:` — the last path segment **is** the manifest, so `tag`
 *   and `prerelease` cannot apply and are ignored (no API call is made);
 * - `file:` / a local path — same, `tag` and `prerelease` are ignored.
 *
 * Signature checking is applied here, after parsing, and only when a public key
 * is configured (`publicKey`, `publicKeys`, `DPX_DESKTOP_PUBLIC_KEY`,
 * `DPX_DESKTOP_PUBLIC_KEYS`). With no key the manifest installs exactly as
 * before, signed or not.
 */
export async function fetchDesktopRelease(source, {
  proxy,
  prerelease = false,
  tag,
  env = process.env,
  timeout,
  apiBase,
  publicKey,
  publicKeys,
  requireSignature,
} = {}) {
  const parsed = parseDesktopSource(source);
  const effectiveProxy = proxy ?? defaultProxy(env);
  const trustedKeys = desktopPublicKeys({ publicKey, publicKeys, env });
  if (parsed.kind === 'file') {
    if (!existsSync(parsed.manifestPath)) {
      throw new Error(`Desktop release manifest not found: ${parsed.manifestPath}`);
    }
    return withSignatureVerdict(parseManifestText(await readFile(parsed.manifestPath, 'utf8'), {
      source: parsed.source,
      manifestUrl: pathToFileURL(parsed.manifestPath).href,
    }), trustedKeys, requireSignature);
  }
  let effectiveTag = tag ?? parsed.tag;
  if (!effectiveTag && prerelease && parsed.kind === 'github') {
    effectiveTag = await resolveLatestPrereleaseTag(parsed.repository, { proxy: effectiveProxy, env, timeout, apiBase });
    // An empty prerelease channel is the same situation as a channel with no
    // published release: `checkDesktopUpdate` maps a 404 to `no-release`, so the
    // check reports it instead of failing the command.
    if (!effectiveTag) {
      throw new HttpError(`No pre-release ${DESKTOP_TAG_PREFIX}* release found in ${parsed.repository}.`, { status: 404 });
    }
  }
  const manifestUrl = desktopManifestUrl(parsed, { tag: effectiveTag });
  const text = await httpGet(manifestUrl, {
    proxy: effectiveProxy,
    headers: { 'User-Agent': DESKTOP_USER_AGENT },
    timeout,
  });
  if (text.status < 200 || text.status >= 300) {
    throw new HttpError(`GET ${manifestUrl} failed with status ${text.status}.`, { status: text.status, url: manifestUrl });
  }
  return withSignatureVerdict(parseManifestText(text.body.toString('utf8'), { source: parsed.source, manifestUrl }), trustedKeys, requireSignature);
}

/**
 * Attach the signature verdict to a manifest.
 *
 * A manifest with no `sig` and no `sigProblem` is returned unchanged, so an
 * unsigned release keeps exactly today's shape (and today's behaviour) when no
 * key is configured.
 */
function withSignatureVerdict(manifest, trustedKeys, requireSignature) {
  if (!trustedKeys.length && !manifest.sig && !manifest.sigProblem) return manifest;
  return { ...manifest, signature: verifyManifestSignature(manifest, { keys: trustedKeys, requireSignature }) };
}

/** Download one release asset, verifying size and digest before returning it. */
export async function downloadDesktopAsset(manifest, { proxy, env = process.env, timeout } = {}) {
  if (!manifest.assetUrl) throw new Error(`Desktop release ${manifest.version} does not declare a downloadable asset.`);
  let buffer;
  if (/^file:/i.test(manifest.assetUrl)) {
    const path = fileURLToPath(manifest.assetUrl);
    if (!existsSync(path)) throw new Error(`Desktop release asset not found: ${path}`);
    buffer = await readFile(path);
  } else if (/^[A-Za-z]:[\\/]/.test(manifest.assetUrl) || manifest.assetUrl.startsWith('\\\\')) {
    buffer = await readFile(manifest.assetUrl);
  } else {
    const response = await httpGetBuffer(manifest.assetUrl, {
      proxy: proxy ?? defaultProxy(env),
      headers: { 'User-Agent': DESKTOP_USER_AGENT, Accept: 'application/octet-stream' },
      timeout,
    });
    buffer = response.body;
  }
  if (manifest.size !== undefined && buffer.length !== manifest.size) {
    throw new Error(`Desktop release ${manifest.version} asset size mismatch: expected ${manifest.size} bytes, received ${buffer.length}.`);
  }
  const digest = sha256Of(buffer);
  if (digest !== manifest.sha256) {
    throw new Error(`Desktop release ${manifest.version} digest mismatch: expected ${manifest.sha256}, received ${digest}.`);
  }
  return { buffer, sha256: digest };
}

async function atomicWrite(path, data) {
  await mkdir(dirname(path), { recursive: true });
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, data);
  await rename(temporary, path);
}

/**
 * Normalize the install time of a stamp into `{ installedAt, installedAtMillis }`.
 *
 * Two writers produce this file: `writeDesktopStamp()` below records an ISO
 * `installedAt`, and the desktop shell's self-update records epoch
 * milliseconds as `installedAtMillis` (`desktop-shell/src-tauri/src/update.rs`).
 * Reading only `installedAt` therefore made the timestamp vanish silently after
 * one shell self-update; both shapes are accepted here and `installedAt` is
 * always populated when either one is present.
 *
 * Returns `{ installedAt: undefined, installedAtMillis: undefined }` when the
 * stamp carries no usable time.
 */
export function normalizeInstalledAt(raw) {
  const iso = typeof raw?.installedAt === 'string' ? raw.installedAt.trim() : '';
  if (iso) {
    const parsed = Date.parse(iso);
    if (Number.isFinite(parsed)) return { installedAt: new Date(parsed).toISOString(), installedAtMillis: parsed };
    return { installedAt: iso, installedAtMillis: undefined };
  }
  const millis = Number(raw?.installedAtMillis ?? raw?.installedAt);
  if (Number.isFinite(millis) && millis > 0) {
    const date = new Date(millis);
    if (!Number.isNaN(date.getTime())) return { installedAt: date.toISOString(), installedAtMillis: millis };
  }
  return { installedAt: undefined, installedAtMillis: undefined };
}

/** A stamp that could not be read, reported explicitly instead of as "absent". */
function damagedDesktopStamp(path, reason, message, schemaVersion) {
  return { damaged: true, reason, path, schemaVersion, message };
}

/**
 * Read the install stamp of one environment.
 *
 * Returns `undefined` when there is no stamp at all, a normalized stamp on
 * success, and an explicit failure object (`{ damaged: true, reason, message }`)
 * when the file exists but cannot be trusted. It never throws: `desktopStatus()`
 * must stay usable on a damaged environment, and both consumers only read
 * optional fields (`stamp?.version`, `stamp?.source`, …), so the failure shape
 * is safe for them — but it no longer looks like "installed by nobody".
 *
 * `schemaVersion` is checked against `DESKTOP_STAMP_SCHEMA_VERSIONS`; an absent
 * or unknown value is reported as damage rather than being read as version 1.
 */
export async function readDesktopStamp(envRoot) {
  const path = desktopStampPath(envRoot);
  if (!existsSync(path)) return undefined;
  let raw;
  try {
    raw = JSON.parse(await readFile(path, 'utf8'));
  } catch (error) {
    return damagedDesktopStamp(path, 'unreadable', `桌面启动器标记文件不是有效 JSON（${path}）：${error.message}`);
  }
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return damagedDesktopStamp(path, 'not-an-object', `桌面启动器标记文件不是 JSON 对象（${path}），视为已损坏。`);
  }
  const schemaVersion = raw.schemaVersion === undefined || raw.schemaVersion === null ? undefined : Number(raw.schemaVersion);
  if (schemaVersion === undefined) {
    return damagedDesktopStamp(path, 'missing-schema', `桌面启动器标记文件没有 schemaVersion（${path}），视为已损坏；跑 dpx desktop install 重新写入。`, undefined);
  }
  if (!Number.isInteger(schemaVersion) || !DESKTOP_STAMP_SCHEMA_VERSIONS.includes(schemaVersion)) {
    const supported = DESKTOP_STAMP_SCHEMA_VERSIONS.join(', ');
    return damagedDesktopStamp(
      path,
      'unsupported-schema',
      `桌面启动器标记文件的 schemaVersion ${JSON.stringify(raw.schemaVersion)} 不受支持（${path}；本版本 dpx 支持 ${supported}），`
        + '视为已损坏；请升级 dpx，或跑 dpx desktop install 重新写入。',
      schemaVersion,
    );
  }
  const { installedAt, installedAtMillis } = normalizeInstalledAt(raw);
  return {
    schemaVersion,
    platform: String(raw.platform ?? DESKTOP_PLATFORM),
    version: raw.version ? String(raw.version) : undefined,
    sha256: normalizeSha256(raw.sha256),
    source: raw.source ? String(raw.source) : 'bundled',
    tag: raw.tag ? String(raw.tag) : undefined,
    installedAt,
    installedAtMillis,
    ...(raw.installedBy ? { installedBy: String(raw.installedBy) } : {}),
  };
}

/**
 * Write the install stamp. Both time shapes are recorded so an older reader on
 * either side (dpx reading `installedAt`, the shell's Rust reader using
 * `installedAtMillis`) finds what it expects.
 */
export async function writeDesktopStamp(envRoot, stamp) {
  const installedAt = stamp.installedAt ?? new Date().toISOString();
  const parsed = Number.isFinite(stamp.installedAtMillis) && stamp.installedAtMillis > 0
    ? stamp.installedAtMillis
    : Date.parse(installedAt);
  await atomicWrite(desktopStampPath(envRoot), `${JSON.stringify({
    schemaVersion: 1,
    platform: stamp.platform ?? DESKTOP_PLATFORM,
    ...stamp,
    installedAt,
    installedAtMillis: Number.isFinite(parsed) ? parsed : Date.now(),
  }, null, 2)}\n`);
}

/** Hash the launcher that is installed in an environment, if any. */
export async function installedDesktopDigest(envRoot) {
  const path = desktopLauncherPath(envRoot);
  if (!existsSync(path)) return undefined;
  return sha256Of(await readFile(path));
}

export async function installedDesktopSize(envRoot) {
  const path = desktopLauncherPath(envRoot);
  if (!existsSync(path)) return undefined;
  return (await stat(path)).size;
}

/**
 * The desktop launcher state of one environment, without network access.
 *
 * A damaged stamp never makes this throw and never blocks an update: the
 * version fields simply come back `undefined`, which is why a damaged stamp is
 * also reported explicitly (`stampDamaged`, `stampReason`, `stampMessage`) and
 * not silently presented as "never installed".
 */
export async function desktopStatus(envRoot) {
  const launcher = desktopLauncherPath(envRoot);
  const present = existsSync(launcher);
  const stamp = await readDesktopStamp(envRoot);
  const damaged = stamp?.damaged === true;
  return {
    envRoot: resolve(envRoot),
    launcher,
    present,
    version: damaged ? undefined : stamp?.version,
    sha256: damaged ? undefined : stamp?.sha256,
    digest: present ? await installedDesktopDigest(envRoot) : undefined,
    source: damaged ? (present ? 'bundled' : undefined) : stamp?.source ?? (present ? 'bundled' : undefined),
    installedAt: stamp?.installedAt,
    installedAtMillis: stamp?.installedAtMillis,
    stampDamaged: damaged,
    ...(damaged ? { stampReason: stamp.reason, stampMessage: stamp.message } : {}),
  };
}

/**
 * Compare the installed launcher with the newest published release.
 * Never writes anything.
 *
 * `available` is the single gate the CLI, the settings window and the Rust
 * shell read, so its rule is spelled out here: **an older release is never
 * available**. `available` is true only when the published version is strictly
 * newer, or when it is the same-or-newer version but a *different build*
 * (same version, different digest — a republished build). A release whose
 * version is older than the installed one always reports `available: false`,
 * even though its digest necessarily differs; that case is also refused by
 * `updateDesktopLauncher()` with `reason: 'newer-installed'`.
 *
 * This mirrors the desktop client's own "only ever upgrade" locks
 * (`allowDowngrade = false` plus a strict `gt()` comparison in
 * `apps/desktop/src/update-coordinator.ts`).
 */
export async function checkDesktopUpdate({
  envRoot,
  source = DEFAULT_DESKTOP_SOURCE,
  proxy,
  prerelease = false,
  tag,
  env = process.env,
  timeout,
  apiBase,
  publicKey,
  publicKeys,
  requireSignature,
} = {}) {
  const current = await desktopStatus(envRoot);
  let release;
  try {
    release = await fetchDesktopRelease(source, { proxy, prerelease, tag, env, timeout, apiBase, publicKey, publicKeys, requireSignature });
  } catch (error) {
    if (error instanceof HttpError && error.status === 404) {
      return { ...current, source, available: false, reason: 'no-release', message: `发布源 ${source} 还没有 desktop 发行版。` };
    }
    throw error;
  }
  if (!current.present) {
    return { ...current, source, latest: release, available: true, reason: 'not-installed', ...signatureSummary(release) };
  }
  const newer = compareVersions(release.version, current.version ?? '0.0.0') > 0;
  const identical = release.sha256 && current.digest === release.sha256;
  const installedNewer = current.version ? compareVersions(release.version, current.version) < 0 : false;
  return {
    ...current,
    source,
    latest: release,
    // Only-upgrade: `newer` is a strict `>`, and the `>= 0` branch must be
    // combined with `!identical` so an older release cannot slip through.
    available: newer || (!identical && compareVersions(release.version, current.version ?? '0.0.0') >= 0),
    // `reason` stays as-is for the shell contract: an older release is reported
    // as `different-build` (with `available: false` and `installedNewer: true`).
    reason: newer ? 'newer-version' : identical ? 'up-to-date' : 'different-build',
    versionMatch: current.version === release.version,
    installedNewer,
    ...signatureSummary(release),
  };
}

/** Signature state of a resolved release, for callers that only print it. */
function signatureSummary(release) {
  return {
    signed: Boolean(release?.sig) || Boolean(release?.sigProblem),
    signatureVerified: release?.signature?.verified === true,
    ...(release?.signature ? { signature: release.signature } : {}),
  };
}

/**
 * Download and install the desktop launcher for one environment.
 *
 * `dryRun` resolves the release and verifies everything without touching the
 * environment. The launcher file itself is replaced atomically; a running
 * launcher cannot be replaced on Windows, which is reported as a clear error
 * instead of a half-written file.
 *
 * Only upgrades land, unless `force` is set. `newer` is a strict `>` version
 * comparison, and an explicitly older release returns
 * `reason: 'newer-installed'` instead of replacing a newer launcher with an
 * older one — mirroring the shell's own "never downgrade, never silently swap
 * the build" door (the shell's `apply()` is being aligned to the same rule).
 * `force` is the only way past both doors, and it is what
 * `dpx desktop install` uses.
 */
export async function updateDesktopLauncher({
  envRoot,
  source = DEFAULT_DESKTOP_SOURCE,
  proxy,
  prerelease = false,
  tag,
  force = false,
  dryRun = false,
  env = process.env,
  timeout,
  apiBase,
  publicKey,
  publicKeys,
  requireSignature,
} = {}) {
  const root = resolve(envRoot);
  const current = await desktopStatus(root);
  const release = await fetchDesktopRelease(source, { proxy, prerelease, tag, env, timeout, apiBase, publicKey, publicKeys, requireSignature });
  const newer = compareVersions(release.version, current.version ?? '0.0.0') > 0;
  const sameDigest = current.present && current.digest === release.sha256;
  if (!force && !newer && sameDigest) {
    return { updated: false, reason: 'up-to-date', current, release, target: desktopLauncherPath(root) };
  }
  if (!force && !newer && !sameDigest && current.version && compareVersions(release.version, current.version) < 0) {
    // Explicit downgrade: the published version is older than what is installed.
    // Without this door a local build newer than the channel would be replaced
    // by the channel's older one, which looks like a successful update.
    return { updated: false, reason: 'newer-installed', current, release, target: desktopLauncherPath(root) };
  }
  if (dryRun) {
    return { updated: false, reason: 'dry-run', current, release, target: desktopLauncherPath(root) };
  }
  const { buffer, sha256 } = await downloadDesktopAsset(release, { proxy, env, timeout });
  const target = desktopLauncherPath(root);
  const staged = `${target}.${process.pid}.new`;
  await mkdir(dirname(target), { recursive: true });
  try {
    await writeFile(staged, buffer);
    await rm(target, { force: true });
    await rename(staged, target);
  } catch (error) {
    await rm(staged, { force: true });
    if (error?.code === 'EPERM' || error?.code === 'EBUSY') {
      throw new Error(`无法替换正在运行的桌面启动器：${target}。请先关闭该桌面程序后重试。`);
    }
    throw error;
  }
  const stamp = {
    version: release.version,
    sha256,
    source: release.source ?? source,
    tag: release.tag,
    installedBy: 'dpx',
    installedAt: new Date().toISOString(),
  };
  await writeDesktopStamp(root, stamp);
  return { updated: true, reason: 'updated', current, release, target, sha256, stamp };
}

/** Install the launcher bundled with this dpx package into an environment. */
export async function installBundledDesktopLauncher({ envRoot, artifactPath, artifactBuffer }) {
  const root = resolve(envRoot);
  const buffer = artifactBuffer ?? await readFile(artifactPath);
  const target = desktopLauncherPath(root);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, buffer);
  const manifest = await readBundledDesktopManifest();
  const sha256 = sha256Of(buffer);
  await writeDesktopStamp(root, {
    version: manifest?.version,
    sha256,
    source: 'bundled',
    tag: manifest?.tag,
    installedBy: 'dpx',
  });
  return { target, sha256, version: manifest?.version };
}
